sudo: required
language: python

services:
  - xvfb

addons:
  chrome: stable

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

install:
  - pip install git+https://github.com/a-maliarov/amazon-captcha-solver

before_script:
  - wget -N https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - whereis chromedriver
  - pip install maliarov
  - pip install coverage
  - pip install codecov

script:
  - coverage run tests/test_main.py

after_success:
  - codecov
