language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install amazoncaptcha

before_script:
  - pip install coverage

script:
  - python tests/test_main.py
  - coverage run tests/test_main.py
